# Generated by Django 5.2.6 on 2025-09-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('face', 'Face'), ('lips', 'Lips'), ('eyes', 'Eyes'), ('eyebrow', 'Eyebrow'), ('hair', 'Hair'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
    ]
