# Generated by Django 5.2.6 on 2025-11-16 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_product_category_order_orderitem'),
        ('product', '0019_product_categories'),
    ]

    operations = [
    ]
