# Generated by Django 5.2.6 on 2025-11-16 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_merge_20251116_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
    ]
