# Generated by Django 5.2.6 on 2025-11-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
