# Generated by Django 5.2.6 on 2025-11-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
